trigger:
- main 

pool:
  name: 'SelfHostedPool'  # De Microsoft-hosted agent, ivm Parallelism

steps:
- script: |
    echo "Hello, World!"
    echo "Agent is working correctly."
  displayName: 'Verify Agent Functionality'

