trigger:
- main  # Vervang 'main' door de naam van je hoofdbranch indien nodig

pool:
  vmImage: 'SelfHostedPool'  # Gebruik een Microsoft-hosted agent

steps:
- script: |
    echo "Hello, World!"
    echo "Agent is working correctly."
    pwd  # Print de huidige directory
    ls -la  # Lijst de bestanden in de huidige directory
  displayName: 'Verify Agent Functionality'
