trigger:
- main

pool:
  vmImage: 'SelfHostedPool' # agent

variables:
  azureSubscription: 'MainServicePrincipal' # Service Principal
  resourceGroupName: 'Resourcegroep1'
  storageAccountName: 'azuredatalakestaging'
  containerName: 'stagingcontainer'
  serverName: 'clientsidesqlserver.database.windows.net'
  databaseName: 'DataFactoryMoestOrgineleNaamHebben'
  adminUsername: 'Tobias'
  adminPassword: '$(adminPassword)' # Beveiligde variabele

steps:
- script: echo Hello, World!
  displayName: 'Run a one-line script'

- script: |
    echo "Testing the agent configuration"
    systeminfo
    date /t
    time /t
  displayName: 'Run a multi-line script'
